{{- if gt (int .Values.controller.replicas) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "foreman-release-operator.fullname" . }}
  labels:
    {{- include "foreman-release-operator.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "foreman-release-operator.selectorLabels" . | nindent 6 }}
{{- end }}
