{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "foreman-stack.serviceAccountName" . }}
  labels:
    {{- include "foreman-stack.labels" . | nindent 4 }}
{{- end }}
