name: Chart checks

on:
  pull_request:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  lint:
    name: Chart Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: azure/setup-helm@bf6a7d304bc2fdb57e0331155b7ebf2c504acf0a # v4
        with:
          version: v4.3.0
      - name: Lint charts
        run: make lint
