apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "foreman.configName" . }}
  labels:
    {{- include "foreman.labels" . | nindent 4 }}
data:
  {{- include "foreman.configurationData" . | nindent 2 }}

