apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "foreman.fullname" . }}-migrate-{{ .Release.Revision }}
  labels:
    {{- include "foreman.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "0"
spec:
  backoffLimit: {{ .Values.migration.backoffLimit }}
  activeDeadlineSeconds: {{ .Values.migration.activeDeadlineSeconds }}
  template:
    metadata:
      labels:
        {{- include "foreman.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migration
    spec:
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 994
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 994
        runAsNonRoot: true
        runAsUser: 994
        seccompProfile:
          type: RuntimeDefault
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: migrate
          image: {{ include "foreman.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - -ec
            - bin/rails db:migrate && bin/rails db:seed
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsGroup: 994
            runAsUser: 994
          env:
            {{- include "foreman.env" . | nindent 12 }}
            - name: SEED_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.foreman.existingSecret }}
                  key: {{ .Values.foreman.seedAdminUserSecretKey }}
            - name: SEED_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.foreman.existingSecret }}
                  key: {{ .Values.foreman.seedAdminPasswordSecretKey }}
          volumeMounts:
            {{- include "foreman.migrationVolumeMounts" . | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: configuration
          configMap:
            name: {{ include "foreman.migrationConfigName" . }}
        - name: temporary
          emptyDir: {}
